class_name Tools
extends Object

const ADJECTIVES := [
    "Funny",
    "Lazy",
    "Turbo",
    "Epic",
    "Sleepy",
    "Morphing",
    "Happy",
    "Sad",
    "Stuffed",
    "Nerdy",
    "Wet",
    "Dry",
    "Huge",
    "Tiny",
    "Sticky",
    "Rounded",
    "Straight",
    "Jumping",
    "Sneaky",
    "Hard",
    "Soft",
    "Unpredictable",
    "Hungry",
    "Tasty",
    "Immortal",
    "Juicy",
    "Sketchy",
    "Underwater"
]

const NOUNS := [
    "Programmer",
    "Penguin",
    "Koala",
    "Fish",
    "Shark",
    "Shrimp",
    "Prawn",
    "Narwhal",
    "Crab",
    "Bongo",
    "Piano",
    "Claus",
    "Pineapple",
    "Apple",
    "Melon",
    "Carrot",
    "Whale",
    "Catto",
    "Doggo",
    "Seagul",
    "Pelican",
    "Snake",
    "Octopus",
    "Rocker",
    "Monster",
    "Peach",
    "Eggplant",
    "Cucumber",
    "Circle",
    "Rectangle",
    "Sphere",
    "Cone",
    "Dodecahedron",
    "Dargon",
    "Pasta",
    "Dumpling"
]

static func generate_name() -> String:
    return ADJECTIVES.pick_random() + " " + NOUNS.pick_random()
